<?php

namespace App\Console\Commands;

use App\Enums\UserRole;
use Illuminate\Console\Command;
use Illuminate\Database\Migrations\DatabaseMigrationRepository;
use Illuminate\Database\Migrations\Migrator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema as SchemaFacade;
use Illuminate\Support\Str;

/**
 * Produces a MySQL .sql file that can be imported through phpMyAdmin.
 *
 * Laravel builds its tables from migrations, so the project has no .sql file
 * of its own and normally needs none: `php artisan migrate --seed` is the
 * supported path. This command exists for the case where that is impossible —
 * a shared hosting plan without SSH, where phpMyAdmin is the only way in.
 *
 * The DDL is rendered by running the real migrations in Laravel's "pretend"
 * mode against the MySQL grammar, so the output is generated from the same
 * migration files the application uses rather than being maintained by hand
 * and drifting out of step with them.
 */
class DumpMysqlCommand extends Command
{
    protected $signature = 'db:mysql-dump
        {--output=database/dumps/temple-passport.sql : Where to write the file}
        {--schema-only : Skip all data, emit tables only}
        {--with-admin : Include an admin account with a generated password}
        {--server-version=8.0.36 : Server version reported to the schema grammar}';

    protected $description = 'Export the schema and seed data as a MySQL .sql file for phpMyAdmin import';

    /**
     * Dump order matters: a parent row must exist before the row that
     * references it, or the import fails on a foreign key.
     */
    /** Throwaway connection name used only for rendering DDL. */
    protected const RENDER_CONNECTION = '__mysql_dump_render';

    protected array $dataTables = [
        'states',
        'districts',
        'deities',
        'temple_categories',
        'facilities',
        'temples',
        'temple_aliases',
        'temple_category_temple',
        'facility_temple',
        'temple_timings',
        'temple_pujas',
        'temple_closures',
        'temple_photos',
    ];

    public function handle(Migrator $migrator): int
    {
        // Captured before schemaSql() swaps the default connection.
        $sourceConnection = config('database.default');

        $path = base_path($this->option('output'));
        File::ensureDirectoryExists(dirname($path));

        $lines = [$this->header()];
        $lines[] = $this->schemaSql($migrator);

        if (! $this->option('schema-only')) {
            $lines[] = $this->dataSql($sourceConnection);
        }

        $adminPassword = null;

        if ($this->option('with-admin')) {
            [$adminSql, $adminPassword] = $this->adminSql();
            $lines[] = $adminSql;
        }

        $lines[] = $this->migrationRowsSql($migrator);
        $lines[] = "SET FOREIGN_KEY_CHECKS = 1;\n";

        File::put($path, implode("\n", $lines));

        $this->info('Wrote '.$this->option('output'));
        $this->line('  Size: '.number_format(File::size($path) / 1024, 1).' KB');

        if ($adminPassword !== null) {
            $this->newLine();
            $this->warn('Admin account included in the dump:');
            $this->line('  Email:    '.config('brand.admin_email', 'admin@example.com'));
            $this->line('  Password: '.$adminPassword);
            $this->warn('  Shown once. Sign in and change it immediately after import.');
        }

        return self::SUCCESS;
    }

    protected function header(): string
    {
        $brand = config('brand.name');

        return <<<SQL
-- {$brand} — MySQL import
--
-- Generated by `php artisan db:mysql-dump` from the project's own migrations.
-- Import through phpMyAdmin when the hosting plan has no SSH access.
--
-- If you DO have SSH, prefer `php artisan migrate --seed` instead: it is the
-- supported path and cannot drift from the migration files.
--
-- Import into an EMPTY database. Importing over existing tables will fail.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

SQL;
    }

    /** Renders every migration as MySQL DDL without touching a MySQL server. */
    protected function schemaSql(Migrator $migrator): string
    {
        $out = ["\n-- ---------------------------------------------------------------\n-- Tables\n-- ---------------------------------------------------------------\n"];

        /*
         * Render against a throwaway clone of the mysql connection, never the
         * shared one.
         *
         * Two things force this. Migrations call Schema:: against the DEFAULT
         * connection, so the default has to point at a MySQL-grammar
         * connection for the duration. And the grammar needs a PDO to answer
         * "is this MariaDB?", which we satisfy with a stub — injecting that
         * stub into the real 'mysql' connection would poison it for the data
         * read that follows, which is fatal when the app itself runs on MySQL.
         */
        $previousDefault = config('database.default');
        $render = self::RENDER_CONNECTION;

        config([
            "database.connections.{$render}" => array_merge(
                config('database.connections.mysql', []),
                ['driver' => 'mysql'],
            ),
            'database.default' => $render,
        ]);

        // The Schema facade caches its resolved builder, which is bound to
        // whichever connection was default when it was first used. Anything
        // earlier in this process that touched Schema would otherwise pin the
        // render to that connection and run the DDL for real against it.
        SchemaFacade::clearResolvedInstances();

        $this->satisfyServerVersionProbe($render);

        try {
            $statements = DB::connection($render)->pretend(function () use ($migrator): void {
                // Laravel's migrator creates the `migrations` table itself, so
                // no migration file defines it. Without this the dump would
                // record migration history into a table it never created.
                //
                // A fresh repository bound explicitly to the render connection,
                // rather than $migrator->getRepository(): commands such as
                // migrate:fresh pin the injected migrator to a named
                // connection, which would send this DDL to the real database.
                $repository = new DatabaseMigrationRepository(app('db'), 'migrations');
                $repository->setSource(self::RENDER_CONNECTION);
                $repository->createRepository();

                foreach ($this->migrationFiles($migrator) as $file) {
                    $migration = require $file;
                    $migration->up();
                }
            });
        } finally {
            config(['database.default' => $previousDefault]);
            DB::purge($render);
            SchemaFacade::clearResolvedInstances();
        }

        foreach ($statements as $statement) {
            $out[] = $this->terminate($statement['query']);
        }

        return implode("\n", $out);
    }

    /**
     * Lets the MySQL grammar answer "is this MariaDB?" without a live server.
     *
     * MySqlGrammar::typeDate() reads PDO::ATTR_SERVER_VERSION, which would
     * otherwise force a real connection just to render a `date` column. The
     * carrier is an in-memory SQLite PDO that is never queried — pretend mode
     * intercepts every statement before it reaches the driver.
     *
     * The reported flavour does not change this schema's output: the MySQL and
     * MariaDB branches differ only for `useCurrent` date defaults and spatial
     * SRIDs, neither of which these migrations use. The dump imports cleanly
     * into MySQL 8 and MariaDB alike, which matters because shared hosts
     * commonly run MariaDB.
     */
    protected function satisfyServerVersionProbe(string $connection): void
    {
        $version = (string) $this->option('server-version');

        $pdo = new class('sqlite::memory:') extends \PDO
        {
            public string $reportedVersion = '8.0.36';

            public function getAttribute(int $attribute): mixed
            {
                if ($attribute === \PDO::ATTR_SERVER_VERSION) {
                    return $this->reportedVersion;
                }

                return parent::getAttribute($attribute);
            }
        };

        $pdo->reportedVersion = $version;

        DB::connection($connection)->setPdo($pdo);
    }

    /** @return array<int, string> */
    protected function migrationFiles(Migrator $migrator): array
    {
        $files = [];

        foreach ($migrator->paths() + [database_path('migrations')] as $path) {
            $files = array_merge($files, glob($path.'/*.php') ?: []);
        }

        sort($files);

        return array_values(array_unique($files));
    }

    protected function dataSql(string $source): string
    {
        $out = ["\n-- ---------------------------------------------------------------\n-- Reference and seed data\n-- ---------------------------------------------------------------\n"];

        foreach ($this->dataTables as $table) {
            // Explicit connection: the render swap above must not be
            // able to redirect the data read.
            $rows = DB::connection($source)->table($table)->get();

            if ($rows->isEmpty()) {
                continue;
            }

            $out[] = "\n-- {$table} ({$rows->count()} rows)";

            // Chunked so a large table does not become one enormous statement
            // that trips phpMyAdmin's upload or execution limits.
            foreach ($rows->chunk(100) as $chunk) {
                $columns = array_keys((array) $chunk->first());
                $columnList = implode(', ', array_map(fn ($c) => "`{$c}`", $columns));

                $values = $chunk
                    ->map(fn ($row) => '('.implode(', ', array_map(
                        fn ($column) => $this->quote(((array) $row)[$column]),
                        $columns,
                    )).')')
                    ->implode(",\n  ");

                $out[] = "INSERT INTO `{$table}` ({$columnList}) VALUES\n  {$values};";
            }
        }

        return implode("\n", $out);
    }

    /** @return array{0: string, 1: string} */
    protected function adminSql(): array
    {
        $password = Str::password(16);
        $hash = Hash::make($password);
        $email = config('brand.admin_email', 'admin@example.com');
        $now = now()->toDateTimeString();

        $sql = "\n-- ---------------------------------------------------------------\n"
            ."-- Admin account\n"
            ."--\n"
            ."-- The password was generated when this file was written and printed\n"
            ."-- to the console once. Change it immediately after signing in, then\n"
            ."-- delete this file — it contains a working credential hash.\n"
            ."-- ---------------------------------------------------------------\n\n"
            ."INSERT INTO `users` (`name`, `email`, `password`, `role`, `is_active`, `created_at`, `updated_at`) VALUES\n"
            .'  ('.$this->quote('Super Admin').', '.$this->quote($email).', '.$this->quote($hash).', '
            .$this->quote(UserRole::SuperAdmin->value).", 1, ".$this->quote($now).', '.$this->quote($now).");\n";

        return [$sql, $password];
    }

    /**
     * Records every migration as already run.
     *
     * Without this, gaining SSH later and running `php artisan migrate` would
     * try to create tables that the import already created, and fail.
     */
    protected function migrationRowsSql(Migrator $migrator): string
    {
        $names = array_map(
            fn (string $file): string => basename($file, '.php'),
            $this->migrationFiles($migrator),
        );

        if ($names === []) {
            return '';
        }

        $values = implode(",\n  ", array_map(
            fn (string $name): string => '('.$this->quote($name).', 1)',
            $names,
        ));

        return "\n-- ---------------------------------------------------------------\n"
            ."-- Migration history\n"
            ."--\n"
            ."-- Marks these migrations as already applied, so a later\n"
            ."-- `php artisan migrate` does not try to recreate these tables.\n"
            ."-- ---------------------------------------------------------------\n\n"
            ."INSERT INTO `migrations` (`migration`, `batch`) VALUES\n  {$values};\n";
    }

    protected function terminate(string $statement): string
    {
        return rtrim(trim($statement), ';').';';
    }

    /** MySQL-safe literal for a value read from the local database. */
    protected function quote(mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        $escaped = str_replace(
            ['\\', "'", "\0", "\n", "\r", "\x1a"],
            ['\\\\', "\\'", '\\0', '\\n', '\\r', '\\Z'],
            (string) $value,
        );

        return "'{$escaped}'";
    }
}
